In [1]:
import numpy as np

# Numpy 배열의 Boolean Indexing
- 다수개의 배열에서 특정 값을 추출할 때
- 배열이름[조건]
- True, False

In [9]:
names = np.array(['a','b','c','d','b','f','g'])
names

array(['a', 'b', 'c', 'd', 'b', 'f', 'g'], dtype='<U1')

In [4]:
names == 'a'

array([ True, False, False, False, False])

In [5]:
data = np.random.randn(7,4)
data

array([[ 5.31937526e-01,  7.39065727e-01,  1.59948538e+00,
         1.50652723e-01],
       [ 1.83510348e-01,  2.54428344e-01, -9.79887564e-01,
        -1.07657191e+00],
       [-3.08755485e-01,  1.98192034e+00,  1.11653601e+00,
         5.37588747e-01],
       [ 3.28993434e+00, -1.39655261e-03,  4.79685212e-01,
        -3.04091265e-01],
       [ 4.50574797e-01,  1.57556377e+00, -9.62410764e-01,
        -1.32002623e-01],
       [-7.60377738e-01, -1.31254159e+00, -5.20192043e-02,
        -1.09202499e+00],
       [-8.91820700e-01, -1.20878736e+00,  4.43925009e-01,
        -4.22185787e-02]])

In [8]:
data[names == 'a']

array([[0.53193753, 0.73906573, 1.59948538, 0.15065272]])

In [10]:
data[names == 'b']

array([[ 0.18351035,  0.25442834, -0.97988756, -1.07657191],
       [ 0.4505748 ,  1.57556377, -0.96241076, -0.13200262]])

# | 연산자 이용

In [11]:
names

array(['a', 'b', 'c', 'd', 'b', 'f', 'g'], dtype='<U1')

In [12]:
(names == 'a') | (names == 'b')

array([ True,  True, False, False,  True, False, False])

In [14]:
data = np.random.randn(3,3)
data

array([[ 0.36219853, -0.67396344,  0.65855081],
       [-0.95595821,  0.42395531,  0.02039585],
       [ 0.87744372,  0.61144617,  1.08027083]])

In [15]:
data > 0

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

# 마스크 적용후 true 값 갯수 구하기
- (조건).sum()

# 

In [16]:
(data>0).sum()

7

# 조건식을 만족하는 실제 값 구하기

In [17]:
data[data>0]

array([0.36219853, 0.65855081, 0.42395531, 0.02039585, 0.87744372,
       0.61144617, 1.08027083])

# 퀴즈

In [19]:
numlist = np.random.randint(1,101,size =20)
numlist

array([99, 31, 31, 50, 57, 11, 57, 63,  3, 64,  8, 99, 78, 80, 63, 82, 51,
       67, 17, 98])

In [21]:
numlist = numlist.reshape(4,5)
numlist

array([[99, 31, 31, 50, 57],
       [11, 57, 63,  3, 64],
       [ 8, 99, 78, 80, 63],
       [82, 51, 67, 17, 98]])

In [22]:
numlist[numlist>50]

array([99, 57, 57, 63, 64, 99, 78, 80, 63, 82, 51, 67, 98])

# 상위 5퍼 숫자 추출

In [23]:
num = np.random.randn(50)
num

array([ 0.51510033,  0.3887128 ,  0.63387138,  1.42371225, -0.7671437 ,
       -2.87223395, -0.71619015,  0.5554624 ,  0.1317192 ,  1.4546932 ,
        1.88714572,  0.16860614, -0.48452875, -0.01625318,  0.44632628,
        0.81941178, -0.81596319,  0.64549718,  0.15991855, -0.51370775,
       -1.33953531, -1.2937226 , -1.91705929,  0.89020733, -0.26301473,
        0.09237493,  0.10569705,  1.047584  , -0.42095149,  1.84672544,
        0.82123964, -0.57915037, -0.17861274, -0.41252293, -0.80583642,
        0.83185758, -0.49717343, -0.24564846, -1.1075604 ,  1.09568671,
        0.32060959,  1.40100722, -0.70315342, -0.06833435,  0.01989039,
       -0.35422943,  1.21739598,  0.55725676,  0.02602089,  0.36553946])

In [24]:
np.sort(num)[::-1]

array([ 1.88714572,  1.84672544,  1.4546932 ,  1.42371225,  1.40100722,
        1.21739598,  1.09568671,  1.047584  ,  0.89020733,  0.83185758,
        0.82123964,  0.81941178,  0.64549718,  0.63387138,  0.55725676,
        0.5554624 ,  0.51510033,  0.44632628,  0.3887128 ,  0.36553946,
        0.32060959,  0.16860614,  0.15991855,  0.1317192 ,  0.10569705,
        0.09237493,  0.02602089,  0.01989039, -0.01625318, -0.06833435,
       -0.17861274, -0.24564846, -0.26301473, -0.35422943, -0.41252293,
       -0.42095149, -0.48452875, -0.49717343, -0.51370775, -0.57915037,
       -0.70315342, -0.71619015, -0.7671437 , -0.80583642, -0.81596319,
       -1.1075604 , -1.2937226 , -1.33953531, -1.91705929, -2.87223395])

In [28]:
temp = int(0.05*len(num))
temp

2

In [29]:
np.sort(num)[::-1][0:temp]

array([1.88714572, 1.84672544])

# 외부 파일 불러오기
- 배열명 = np.loadtxt('파일경로',delimiter='구분자',dtype=데이터형)
- np.savetxt('파일경로', 배열이름.fmt='포맷형식', delimiter = '구분자')

In [31]:
data = np.loadtxt('data/ratings.dat', delimiter='::', dtype=np.int64)
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [32]:
data.shape

(1000209, 4)

In [34]:
data[:200,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [35]:
data[:10, 2]

array([5, 3, 3, 4, 5, 3, 5, 5, 4, 4], dtype=int64)

In [39]:
data[:,2].mean()

3.581564453029317

# csv 파일로 저장

In [45]:
data = np.loadtxt('data/ratings.dat', delimiter='::', dtype=np.int64) 
data2 = data[:10,:]
data2

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368]], dtype=int64)

In [46]:
np.savetxt('data.csv', data2, fmt='%.3f', delimiter=',')