# random 모듈
- 외부 모듈 : import random
- random.random
- random.randint(최소, 최대)
- random.randrange(시작, 끝, 간격)
- random.uniform(최소, 최대)

In [1]:
import random

In [2]:
random.random()

0.34783450822620166

In [4]:
random.randint(0,100)

75

In [9]:
random.randrange(2,101,2)

98

In [7]:
random.randrange(1,101,2)

79

In [10]:
random.uniform(-1,-2)

-1.3840213921604154

# random.choice()
- 리스트에서 임의의 원소 출력

In [11]:
random.choice?

In [12]:
random.choice(['a','b','c','d','e'])

'a'

# random.sample()
- random.sample(집합형자료,갯수)

In [13]:
numlist = ['a','b','c','d','e']
random.sample(numlist,3)

['e', 'c', 'b']

In [14]:
random.sample(numlist,2)

['a', 'b']

In [15]:
import numpy as np

# Numpy 배열의 난수값 지정하기
- np.random.rand(갯수)
- np.random.rand(행수,열수)
- 0부터 1사이에서 실수 난수를 생성

In [16]:
np.random.rand(5)

array([0.77305654, 0.43343911, 0.68461148, 0.41684425, 0.62011525])

In [17]:
np.random.rand(2,3)

array([[0.88379517, 0.21536847, 0.07976067],
       [0.17976985, 0.38642994, 0.66950387]])

# Numpy 배열의 난수값 지정하기 : randint()
- np.random.randint(low, high, size = 갯수): 1차
- np.random.randint(low, high, size = (행,열)): 2차
- high를 입력하지 않으면 0과 low 사이의 숫자, high를 입력하면 low 와 high 사이의 숫자를 출력한다

In [18]:
np.random.randint(1,10,size=3)

array([4, 3, 9])

In [19]:
np.random.randint(-10,11,size=5)

array([ 7, -1, -8,  0,  5])

In [22]:
np.random.randint(10,20, size =(3,5))

array([[11, 17, 11, 15, 12],
       [10, 17, 15, 18, 15],
       [16, 10, 19, 10, 10]])

# np.random.seed()
- 한번 발생한 난수를 다시 표시할 때 사용 => 시드 메모리에 기억
- np.random.seed(숫자)
- 숫자는 0~양수
- np.random.seed(숫자)로 시드 지정 후 난수 생성
- 난수 호출때에도 다시 np.random.seed(숫자)로 시드 지정 후 난수 생성
- 과거 난수 사용

In [23]:
np.random.seed(0)
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [24]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [25]:
np.random.seed(0)
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [27]:
np.random.seed(123)
np.random.randint(10)

2

In [31]:
np.random.randint(10)

3

In [32]:
np.random.seed(123)
np.random.randint(10)

2

In [33]:
np.random.seed(54321)
np.random.randn(3,3)

array([[ 0.22397889,  0.7445909 , -0.33426894],
       [ 1.38917151, -2.29609451,  1.14120478],
       [ 0.05544775, -0.08276013, -0.65168766]])

In [34]:
np.random.randn(3,3)

array([[-0.01602191, -0.57446469,  0.04814256],
       [ 0.49949734,  0.15539682,  0.76254251],
       [ 0.56048876,  0.33248345, -0.54542288]])

In [35]:
np.random.seed(54321)
np.random.randn(3,3)

array([[ 0.22397889,  0.7445909 , -0.33426894],
       [ 1.38917151, -2.29609451,  1.14120478],
       [ 0.05544775, -0.08276013, -0.65168766]])

# np.random.choice()
- 리스트에서 무작위로 n개의 데이터를 추출할 때 사용한다
- np.random.choice(데이터형은 숫자/리스트, size = 샘플숫자, replace = True/False, p = 리스트)
- 데이터형이 리스트이면 데이터, 정수이면 arange(a) 명령으로 데이터를 생성한다.
- size : 정수, 샘플 숫자
- replace : bool, True이면 한번 선택한 데이터를 다시 선택 가능, 중복허용
- p : 리스트형태, 각 데이터가 선택 될 수 있는 확률로 소숫점 단위로 지정

In [36]:
np.random.choice(11, size=4, replace=True)

array([7, 8, 6, 7])

In [37]:
np.random.choice(11, size=4, replace=False)

array([1, 9, 5, 8])

In [42]:
np.random.choice(11, size=12, replace=True)

array([ 8,  3, 10, 10,  9,  2, 10,  6,  9,  3,  7,  6])

In [68]:
# 선택 확률을 다르게 해서 2개 선택
# 0~4 범위에서 0,1,2,3,4, 숫자중 2개 선택
# p는 아이템의 갯수만큼 리스트로 구성
# p 의 값은 0~1 소숫점으로 표시
np.random.choice(5, size=2, p =[ 0, 0.3, 0.3, 0.4, 0])

array([2, 3], dtype=int64)

In [110]:
np.random.choice(['꽝','하와이 왕복티켓','스타벅스 상품권'],1,p=[0.7,0.05,0.25])

array(['꽝'], dtype='<U8')

# np.random.shuffle()
- 데이터의 순서바꾸기
- np.random.shuffle(집합형자료)

In [165]:
myList = [10, 30, 100, 5, 33, 99, 2]
myList


[10, 30, 100, 5, 33, 99, 2]

In [168]:
np.random.shuffle(myList)
myList = [10, 30, 100, 5, 33, 99, 2]
myList

[10, 30, 100, 5, 33, 99, 2]

In [137]:
np.random.choice(46,3,False)

array([ 2, 41, 24])

In [140]:
np.random.shuffle?


In [157]:
arr1 = np.array([3.23423,4.23423415,5.1155151])
arr1

array([3.23423   , 4.23423415, 5.1155151 ])

In [161]:
# 기본 소숫점을 3번째 자리에서 반올림
np.set_printoptions(precision=2)

In [162]:
arr1 = np.array([3.23423,4.23423415,5.1155151])
arr1

array([3.23, 4.23, 5.12])

In [169]:
np.set_printoptions(precision=4)

In [170]:
arr1 = np.array([3.23423,4.23423415,5.1155151])
arr1

array([3.2342, 4.2342, 5.1155])

In [171]:
np.sqrt([1,2,3,4,5])

array([1.    , 1.4142, 1.7321, 2.    , 2.2361])

In [172]:
np.log10([10,100,2000])

array([1.   , 2.   , 3.301])

In [176]:
ndarray = np.arange(1,11)


In [177]:
np.set_printoptions(precision=3)

In [178]:
np.log10(ndarray)

array([0.   , 0.301, 0.477, 0.602, 0.699, 0.778, 0.845, 0.903, 0.954,
       1.   ])

In [179]:
np.sqrt(ndarray)

array([1.   , 1.414, 1.732, 2.   , 2.236, 2.449, 2.646, 2.828, 3.   ,
       3.162])

# 두개중 작은거 큰거 추출
- np.maximum(배열1,배열2)
- np.minimum(배열1,배열2)

In [180]:
arr1 = np.random.randn(10)
arr1

array([-0.016,  1.895, -0.325,  0.947,  0.47 , -0.495,  0.646, -0.985,
       -1.762, -0.65 ])

In [182]:
arr2 = np.random.randn(10)
arr2

array([ 0.299,  1.061, -0.096, -2.201, -0.33 , -0.572,  1.422, -0.492,
        0.333,  0.408])

In [184]:
arr3 = np.maximum(arr1,arr2)
arr3

array([ 0.299,  1.895, -0.096,  0.947,  0.47 , -0.495,  1.422, -0.492,
        0.333,  0.408])

In [185]:
arr3 = np.minimum(arr1,arr2)
arr3

array([-0.016,  1.061, -0.325, -2.201, -0.33 , -0.572,  0.646, -0.985,
       -1.762, -0.65 ])

# np.argmax(), np.argmin()
- 배열내 최대값 또는 최소값의 인덱스를 반환
- np.argmax(배열명), np.argmin(배열명)
- np.argmax(배열명, axis=0)세로방향, np.argmin(배열명, axis=1)가로방향

In [187]:
arrA= ([1, 100, -10, 45, 33 ,50 ,200])
arrA

[1, 100, -10, 45, 33, 50, 200]

In [188]:
np.argmax(arrA)

6

In [189]:
np.argmin(arrA)

2

In [190]:
arrB = ([1,2,4,7],[9,88,6,45],[100,6,4,88])
arrB

([1, 2, 4, 7], [9, 88, 6, 45], [100, 6, 4, 88])

In [192]:
# 세로열
np.argmax(arrB, axis=0)

array([2, 1, 1, 2], dtype=int64)

In [195]:
# 가로행
np.argmax(arrB, axis=1)

array([3, 1, 0], dtype=int64)

In [196]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [197]:
arr1.sum()

55

In [198]:
# 평균
arr1.mean()

5.5

In [199]:
arr2 = np.random.randn(3,3)
arr2

array([[ 0.095, -0.657,  1.293],
       [-0.233,  0.167,  0.429],
       [ 0.388,  0.322, -0.581]])

In [200]:
arr2.sum()

1.2227845645722817

In [201]:
arr2.mean()

0.13586495161914242

In [202]:
# 세로합
arr2.sum(axis=0)

array([ 0.25 , -0.168,  1.141])

In [203]:
# 가로합
arr2.sum(axis=1)

array([0.731, 0.362, 0.13 ])

In [205]:
arr2dint = np.random.randint(1,21,size=(3,2))
arr2dint

array([[11,  9],
       [17, 11],
       [ 8,  4]])

In [206]:
arr2dint.sum(axis=0)

array([36, 24])

In [207]:
arr2dint.sum(axis=1)

array([20, 28, 12])

In [208]:
arr2dint.mean(axis=0)

array([12.,  8.])

In [209]:
arr2dint.mean(axis=1)

array([10., 14.,  6.])

# Numpy 배열의 병합
- np.vstack((배열명1,배열명2)): 행으로 합치기
- np.hstack((배열명1,배열명2)): 열로 합치기

In [210]:
a = np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [212]:
b = np.array([[4],[5],[6]])
b

array([[4],
       [5],
       [6]])

In [213]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [215]:
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

# Numpy 배열의 병합(concatenate)2
- 가로 세로 방향으로 넘파이 배열 합치기
- np.concatenate((배열1,배열2),axis = 0/1)

In [216]:
np.concatenate((a,b),axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [217]:
np.concatenate((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

# 행렬 곱
- 배열1.dot(배열2)

In [219]:
a= np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [220]:
b = np.arange(7,13).reshape(3,2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [221]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

# 정렬과 관련된 함수 이용하기 -1차원
- np.sort(배열이름) : 오름차순
- np.sort(배열이름)[::-1] :내림차순

In [224]:
arr = np.random.randn(10)
arr

array([ 0.262, -0.608,  0.038, -0.722,  0.033, -1.276,  0.059, -0.262,
        1.356, -0.448])

In [225]:
np.sort(arr)

array([-1.276, -0.722, -0.608, -0.448, -0.262,  0.033,  0.038,  0.059,
        0.262,  1.356])

In [226]:
np.sort(arr)[::-1]

array([ 1.356,  0.262,  0.059,  0.038,  0.033, -0.262, -0.448, -0.608,
       -0.722, -1.276])

In [228]:
arr2d = np.random.randn(3,4)
arr2d

array([[ 0.613,  0.825,  1.281, -0.425],
       [-0.719,  1.976, -1.588,  1.635],
       [-1.049, -0.118,  0.376,  1.889]])

In [229]:
np.sort(arr2d,axis=0)

array([[-1.049, -0.118, -1.588, -0.425],
       [-0.719,  0.825,  0.376,  1.635],
       [ 0.613,  1.976,  1.281,  1.889]])

In [230]:
np.sort(arr2d,axis=1)

array([[-0.425,  0.613,  0.825,  1.281],
       [-1.588, -0.719,  1.635,  1.976],
       [-1.049, -0.118,  0.376,  1.889]])

In [231]:
np.sort(arr2d,axis=0)[::-1]

array([[ 0.613,  1.976,  1.281,  1.889],
       [-0.719,  0.825,  0.376,  1.635],
       [-1.049, -0.118, -1.588, -0.425]])

In [232]:
np.sort(arr2d,axis=1)[::-1]

array([[-1.049, -0.118,  0.376,  1.889],
       [-1.588, -0.719,  1.635,  1.976],
       [-0.425,  0.613,  0.825,  1.281]])

# 중복값 제거하기
- np.unique(배열명)

In [233]:
names = np.array(['a','b','c','a','d','b'])
names

array(['a', 'b', 'c', 'a', 'd', 'b'], dtype='<U1')

In [234]:
np.unique(names)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [237]:
set(names)

{'a', 'b', 'c', 'd'}

# 단위행렬(Identity)
- 대각선의 원소가 모두 1이며, 나머지 원소는 모두 1인 구조는 정사각 행렬
- np.identity(대각선 숫자)
- np.identity(n=대각선숫자,dtype=데이타형)

In [238]:
# 데이터형 실수
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [240]:
# 데이터형 정수
np.identity(n=5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [241]:
# 데이터형 문자열
np.identity(n=7, dtype=str)

array([['1', '', '', '', '', '', ''],
       ['', '1', '', '', '', '', ''],
       ['', '', '1', '', '', '', ''],
       ['', '', '', '1', '', '', ''],
       ['', '', '', '', '1', '', ''],
       ['', '', '', '', '', '1', ''],
       ['', '', '', '', '', '', '1']], dtype='<U1')

# 대각선이 1인 행렬만들기
- np.eye(N=1의 숫자, M=열수, dtype=데이터형)
- np.eye(1의 숫자), 단위행렬과 같다, 정사각형 구조
- np.eye(1의 숫자,열수 k=startindex)
- 행수와 열수가 달라도 된다

In [242]:
np.eye(N=3,M=4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [243]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [244]:
np.eye(4,7,k=2)

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

In [245]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [246]:
np.eye(3,7,k=2)

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

# 대각행렬의 값을 추출함 : np.diag()
- np.diag(배열이름)
- np.diag(배열이름, k=startindex)

In [248]:
matrix = np.arange(9).reshape(3,3)
matrix


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [249]:
np.diag(matrix)

array([0, 4, 8])

In [250]:
np.diag(matrix,k=1)

array([1, 5])

# 조건식

In [251]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [252]:
a <0

array([False, False, False, False, False, False, False, False, False,
       False])

In [253]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

# All, Any
- any(조건식) => or
- all(조건식) => and

In [255]:
np.any(a<5)

True

In [256]:
np.all(a<5)

False

In [257]:
np.all(a>5), np.all(a<0)

(False, False)

In [258]:
np.all(a<100)

True

# 비교 연산1- 두개의 배열
- numpy는 배열간의 크기가 동일할 때 원소간 비교의 결과를 Boolean Type 으로 반환하여 돌려준다

In [259]:
test_a = np.array([1,5,7])
test_b = np.array([5,2,1])

In [260]:
test_a > test_b

array([False,  True,  True])

In [261]:
test_a == test_b

array([False, False, False])

# 비교연산 2
- np.logical_and(조건식1,조건식2)
- np.logical_not(조건식)
- np.logical_or(조건식1, 조건식2)

In [262]:
a = np.array([1,9,0])
a

array([1, 9, 0])

In [263]:
np.logical_and(a>0, a<10)

array([ True,  True, False])

In [264]:
np.logical_or(a>0, a<10)

array([ True,  True,  True])

In [265]:
np.logical_not(a<5)

array([False,  True, False])

# np.where
- np.where(조건식,True,False): 조건식에 만족하면 True, 아니면 False
- np.where(조건식): 조건식에 만족하면 인덱스 값 표시

In [266]:
a = np.array([1, 3, 0])
a

array([1, 3, 0])

In [267]:
np.where(a>1,5,10)

array([10,  5, 10])

In [268]:
np.where(a>5,5,10)

array([10, 10, 10])

In [271]:
np.where(a==1,5,10)

array([ 5, 10, 10])

In [272]:
b = np.arange(5, 16)
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [273]:
b> 10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [274]:
np.where(b>10)

(array([ 6,  7,  8,  9, 10], dtype=int64),)

# np.isnan()
- np.isnan(넘파이배열명)
- null 값인지 true/false
- np.NaN => 넘파이배열에서 null값을 의미함

In [276]:
c = np.array([np.NaN, 0, 4, 1.5])
c

array([nan, 0. , 4. , 1.5])

In [277]:
np.isnan(c)

array([ True, False, False, False])