# 넘파이란?
- Numeric + Python = Numpy
- 수학 및 과학 연산을 위한 파이썬 패키지
- 관련 사이트 : http://www.numpy.org
- 리스트와의 차이점: 하나의 데이터형만 받음
- 주의사항 : numpy 외부 모들을 import 하고 사용

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

### 넘파이 배열 만들기

In [3]:
arrA = [1, 2, 3, 4, 5]
print(arrA, type(arrA))

[1, 2, 3, 4, 5] <class 'list'>


In [4]:
matrixA = np.array(arrA)
print(matrixA,type(matrixA))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
matrixB = np.array([0.45, 5.5, 0, 3.34])
matrixB

array([0.45, 5.5 , 0.  , 3.34])

In [6]:
matrixC = np.array(['a', 'b', 'c'])
matrixC

array(['a', 'b', 'c'], dtype='<U1')

## 자동 캐스팅
- 숫자 + 문자 => 문자
= 정수 + 실수 => 실수

In [7]:
matrixD = np.array([1, 2, 3, 'banana', 'cat'])
matrixD

array(['1', '2', '3', 'banana', 'cat'], dtype='<U11')

# 넘파이배열의 속성
- 배열명.shape : 구조
- 배열명.ndim : 차원
- 배열명.size : 전체갯수

In [8]:
arr1d = np.array([1, 4, 5, 10])
arr1d

array([ 1,  4,  5, 10])

In [9]:
arr1d.shape

(4,)

In [10]:
arr1d = np.array([[ 1,  4,  5, 10],[ 2,  7,  8, 9 ]] )
arr1d

array([[ 1,  4,  5, 10],
       [ 2,  7,  8,  9]])

In [11]:
arr1d.shape

(2, 4)

In [12]:
arr1d.ndim

2

In [13]:
arr1d.size

8

In [14]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arr2 = np.zeros([2,2])

In [16]:
arr2

array([[0., 0.],
       [0., 0.]])

In [17]:
arr3 = np.ones(10)
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
arr3 = np.ones([3,3])
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
arr4 = np.empty([2,2])
arr4

array([[0., 0.],
       [0., 0.]])

In [20]:
arr5 = np.empty(10)
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 초기값을 1씩 증가되는 숫자값으로 지정하기
- np.arange(start,end,step)

In [21]:
range(10)

range(0, 10)

In [22]:
range(1,11)

range(1, 11)

In [23]:
range(0,11,2)

range(0, 11, 2)

In [24]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [25]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [27]:
np.arange(1,30,5)

array([ 1,  6, 11, 16, 21, 26])

# Numpy 배열의 구조 변경
- 배열명.reshape(행수,열수)
- Element의 갯수는 동일하고 구조 변경
- 배열명.reshape(-1,행안의 아이템수):size를 기반으로 row 개수 선정

# 2차원 배열 만들어 구조 변경하기
- arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
- arr1

In [28]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
myArray = np.array([10, 20, 30 ,40, 50 ,60])
myArray

array([10, 20, 30, 40, 50, 60])

In [31]:
myArray.reshape(-1,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [32]:
myArray.reshape(-1,3)

array([[10, 20, 30],
       [40, 50, 60]])

# flatten() 으로 1차원 배열로 변경하기

In [33]:
myArray = np.array([[10, 20],
       [30, 40],
       [50, 60]])
myArray
myArray.flatten()

array([10, 20, 30, 40, 50, 60])

# 데이타형 표시와 변경
- type(변수/집합형...):데이터형 표시
- 배열명.dtype : data type
- 배열명.astype(데이터명): 데이터형변환 => 캐스팅

...
    데이터형
...

In [34]:
# 정수형 넘파이 배열
arr1 = np.array([1,2,3,4,5])

In [35]:
type(arr1)

numpy.ndarray

In [36]:
arr1.dtype

dtype('int32')

In [37]:
arr2 = np.array([1.1,2.4,3,4,5])
arr2.dtype

dtype('float64')

# 정수형 => 실수형 배열로 변경

In [38]:
arr1 = np.array([1, 2, 3, 4, 5])

In [39]:
arr1.dtype

dtype('int32')

In [40]:
arr2 = arr1.astype(float)
arr2

array([1., 2., 3., 4., 5.])

In [41]:
arr2.dtype

dtype('float64')

In [42]:
arr3 = np.array([1.2, 2.5, 3.6, 4.1, 5.3])
arr3

array([1.2, 2.5, 3.6, 4.1, 5.3])

In [43]:
arr4 = arr3.astype(int)
arr4

array([1, 2, 3, 4, 5])

In [44]:
arr1 = np.arange(20,26)
arr2 = np.arange(10,16)
print(arr1,arr2)

[20 21 22 23 24 25] [10 11 12 13 14 15]


In [45]:
arr1 + arr2

array([30, 32, 34, 36, 38, 40])

In [46]:
arr1 - arr2

array([10, 10, 10, 10, 10, 10])

In [47]:
arr1 * arr2

array([200, 231, 264, 299, 336, 375])

In [48]:
arr1 / arr2

array([2.        , 1.90909091, 1.83333333, 1.76923077, 1.71428571,
       1.66666667])

# 행렬의 인덱싱과 슬라이싱 -1차원
- 리스트와 비슷
- 배열이름[인덱스번호]
- 배열이름[start:end]

In [49]:
animals =([100, 200, 300, 400])
animals

[100, 200, 300, 400]

In [50]:
animals[0]

100

In [51]:
animals[-1]

400

In [52]:
animals[0:2]

[100, 200]

# 행렬의 인덱싱과 슬라이싱 -2차원
- 리스트와 비슷
- 배열이름[행 열] / 배열이름[행][열]
- 배열이름[:,:] 전체출력
- 배열이름[start:end, start:end]

In [53]:
myArray = np.arange(1,31)
myArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
newArray = myArray.reshape(-1,6)
newArray

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [55]:
newArray[0][5]

6

In [56]:
newArray[0,5]

6

In [57]:
newArray[:,0]

array([ 1,  7, 13, 19, 25])

In [58]:
newArray[0,:]

array([1, 2, 3, 4, 5, 6])

In [59]:
newArray[:,2]

array([ 3,  9, 15, 21, 27])

In [60]:
newArray[0:2,:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [61]:
newArray[2:,3:]

array([[16, 17, 18],
       [22, 23, 24],
       [28, 29, 30]])

# ::이용한 슬라이싱
- 배열이름[start:end:step]
- 배열이름[start:end:step, [start:end:step]]

In [62]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr1[::2]

array([1, 3, 5, 7, 9])

In [64]:
arr1[1::2]

array([ 2,  4,  6,  8, 10])

In [65]:
arr1[0:5:2]

array([1, 3, 5])

In [66]:
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [67]:
arr2[::2,:]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [68]:
arr2[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [69]:
marr = np.arange(1,16).reshape(-1,3)
marr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [70]:
marr[::2]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [71]:
marr = np.arange(1,16).reshape(-1,5)
marr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [72]:
marr[::2,::3]

array([[ 1,  4],
       [11, 14]])