# numpy quiz 1

In [1]:
import numpy as np

In [5]:
myArray = np.array(['강아지', '원숭이', '꽃', '45', '100'])
myArray


array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')

In [8]:
print('차원 :', myArray.ndim)

차원 : 1


In [11]:
print('데이터형 :', myArray.dtype)

데이터형 : <U3


In [12]:
print('전체구조 :', myArray.shape)

전체구조 : (5,)


In [15]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
myArray = np.arange(51,81).reshape(-1,5)
myArray

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

In [19]:
myArray.astype(float)

array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])

In [20]:
myArray.astype(float).dtype

dtype('float64')

In [21]:
myArray = np.array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
myArray

array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])

In [22]:
myArray.flatten()

array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])

In [24]:
myArray.flatten()[5:-1]

array([23, 45, 67,  8,  4,  6])

In [32]:
myArray = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
myArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
myArray[0] = 10
myArray[7:] = 0
myArray

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])